### ISSUE TITLE
Trying to get property 'importers' of non-object

### ISSUE THREAD

**Issue by EmptyStreets** [barrelstrength/craft-sprout-import#14]
Fresh install of Craft RC 17.1

Right after the plugin installation and by clicking on the sprout import tab I see this:
 
[yii_base_ErrorException.pdf](https://github.com/barrelstrength/craft-sprout-import/files/1865674/yii_base_ErrorException.pdf)

**Comment by BenParizek** [comment]
Thanks for reporting. This has been fixed in the latest release `v1.0.0-beta.4`.
