### ISSUE TITLE
Importing parent categories

### ISSUE THREAD

**Issue by EmptyStreets** [barrelstrength/craft-sprout-import#16]
How do I specify the parent category (categories) while importing the category elements?

**Comment by BenParizek** [comment]
The most simple approach for this is to import your categories flat and update their hierarchy once you import them. Often, it also helps to import the categories before other related elements that you may be importing afterwards as well. Once the categories are in, you can us the `matchElement` flag to match categories based on a slug or legacy ID custom field to help get things mapped.

To import with hierarchy it can get tricky as you have to know the `parentIds` (which may or may not exist). We'll likely try to make this process a bit easier in the future, but this mostly just has to be figured out as you prep the import right now.

**Comment by EmptyStreets** [comment]
Ben can you please post a sample snippet to import the sub/child category with its parent id of let's say 5?

**Comment by BenParizek** [comment]
@pdaleramirez I haven't had a chance to get to this. Could you post an example of importing parent categories when you have a chance? Or is this a feature request? Maybe we can more easily do this with the new `afterSaveElement` behavior added for Entry Versions.

Another question on the topic here: https://craftcms.stackexchange.com/questions/25996/importing-entries-under-a-parent-with-sprout-import-using-related-key

**Comment by pdaleramirez** [comment]
The way you can import categories with a parentId is assign a `newParentId: 99` attribute
```
[
  {
    "@model": "barrelstrength\\sproutimport\\importers\\elements\\Category",
    "attributes": {
      "groupId": 1,
      "slug": "category-slug",
      "dateCreated": "2016-01-13 01:25:57",
      "dateUpdated": "2016-01-13 01:25:57",
      "enabled": true,
      "newParentId": 99
    },
    "content": {
      "title": "Category Title",
      "fields": {
        "firstPlain": "sdfsd"
      }
    }
  }
]
```
I also added a new feature where you can assign a slug value to `parentSlug: category-slug`
E.g.
```
[  
 {
    "@model": "barrelstrength\\sproutimport\\importers\\elements\\Category",
    "attributes": {
      "groupId": 1,
      "slug": "category-slug-child",
      "dateCreated": "2016-01-13 01:25:57",
      "dateUpdated": "2016-01-13 01:25:57",
      "enabled": true
    },
    "content": {
      "title": "Category Child",
      "fields": []
    },
    "parentSlug": "category-slug"
  }
]
```

**Comment by BenParizek** [comment]
@EmptyStreets This has been improved in the latest release now available in the plugin store. More details on the Categories doc page:
https://sprout.barrelstrengthdesign.com/docs/import/categories.html#hierarchy

In short, you can now match parents by looking up their element IDs using whatever criteria you would like. This example looks up the `newParentId` using the `slug` value:

``` json
[  
 {
    "@model": "barrelstrength\\sproutimport\\importers\\elements\\Category",
    "attributes": {
      "groupId": 1,
      "slug": "category-slug-child",
      "dateCreated": "2016-01-13 01:25:57",
      "dateUpdated": "2016-01-13 01:25:57",
      "enabled": true,
      "related": {
        "newParentId": {
          "@model": "barrelstrength\\sproutimport\\importers\\elements\\Category",
          "params": {
            "slug": "category-slug"
          }
        }
      }
    },
    "content": { ... }
  }
]
```
