### ISSUE TITLE
Import user into groups

### ISSUE THREAD

**Issue by Coysh** [barrelstrength/craft-sprout-import#17]
This might be a feature request, but I can't see anything in the documentation to add users to a group.

UPDATE: This might be a feature request (https://craftcms.stackexchange.com/a/22810/8039)

**Comment by BenParizek** [comment]
@Coysh Support for importing Users into Groups has been added in the latest release:
https://sprout.barrelstrengthdesign.com/docs/import/users.html#user-groups
