### ISSUE TITLE
What is the significance of matrix object keys?

### ISSUE THREAD

**Issue by colinmeinke** [barrelstrength/craft-sprout-import#23]
For example, `new1` here https://github.com/barrelstrength/craft-sprout-import/blob/v1/src/examples/content/craft/elements/Entries-MatrixField.json#L20

Where does this name get used? Does it have to be called `new${n}`?

**Comment by BenParizek** [comment]
@colinmeinke `newX` is Craft's convention for creating new Matrix blocks. You can observe this if you create a new Entry that has a Matrix Field in the Control Panel and then add multiple matrix blocks and inspect the Matrix input fields code before submitting the page:
https://github.com/craftcms/cms/blob/develop/src/templates/_components/fieldtypes/Matrix/input.html#L10

It's just used as a placeholder which is then saved as a Matrix Block with an ID. When editing an existing Matrix Field, the blocks should have IDs.
