### ISSUE TITLE
Add version when updating a versionable entry

### ISSUE THREAD

**Issue by colinmeinke** [barrelstrength/craft-sprout-import#27]
Sections can support versioning, where when an entry is saved it also adds a row to the `entryversions` table. It would be great if Sprout Import took care of this automatically when creating a new entry, and updating existing entries.

**Comment by colinmeinke** [comment]
To give a use case. In many of our templates we use versions directly, instead of the entry itself. For example, for legal documents, which are versionable in real life. Lets say when a user visits `/legal/2`, we want to display the second version of the entry, not the latest version. Craft's versions system is a great match for this, and we can do something like this in the template:

```
{% set requestedVersion = craft.app.request.segments[ 1 ] %}
{% set site = craft.app.sites.getSiteByHandle('us') %}
{% set entry = craft.entries.section('legal').site(site.handle).one() %}
{% set versions = craft.app.entryRevisions.getVersionsByEntryId(entry.id, site.id, null, true, true) %}
{% set displayVersion = {} %}

{% for v in versions %}
  {% set version = v.num %}

  {% if version == requestedVersion %}
    {% set displayVersion = v %}
  {% endif %}
{% endfor %}

{% block content %}
  <p>{{ displayVersion.content }}</p>
{% endblock %}
```

This all works great, the only problem being that Sprout Import does not add rows to the `entryversions` table on import.

My import data might look something like this. I have an array where the first item should create the entry (and the first row in the `entryversions` table), and the following two items should update the newly created entry (and add two more rows to the `entryversions` table):

```
[
    {
      "@model": "barrelstrength\\sproutimport\\integrations\\sproutimport\\elements\\Entry",
      "attributes": {
        "authorId": 1,
        "siteId": 2,
        "sectionId": 1,
        "typeId": 1,
        "slug": "legal-us"
      },
      "content": {
        "title": "Legal - US",
        "fields": {
          "content": "Hello world v1"
        }
      }
    },
    {
      "@model": "barrelstrength\\sproutimport\\integrations\\sproutimport\\elements\\Entry",
      "attributes": {
        "authorId": 1,
      },
      "content": {
        "title": "Legal - US",
        "fields": {
          "content": "Hello world v2"
        }
      },
      "settings": {
        "updateElement": {
          "matchBy": "slug",
          "matchValue": "legal-us",
          "matchCriteria": {
            "siteId": 2,
            "sectionId": 1
          }
        }
      }
    },
    {
      "@model": "barrelstrength\\sproutimport\\integrations\\sproutimport\\elements\\Entry",
      "attributes": {
        "authorId": 1,
      },
      "content": {
        "title": "Legal - US",
        "fields": {
          "content": "Hello world v3"
        }
      },
      "settings": {
        "updateElement": {
          "matchBy": "slug",
          "matchValue": "legal-us",
          "matchCriteria": {
            "siteId": 2,
            "sectionId": 1
          }
        }
      }
    }
]
```

Sprout Import creates the entry, and updates it twice, but does not add rows to the `entryversions` table.

My proposal is, that when Sprout Import is doing it's thing and creating/updating the entry's `content` table row, it should also check if the section type if "versionable", and if so add a new row to the `entryversions` table. This would then match Craft's behaviour when creating/updating "versionable" section entries via the admin UI.

**Comment by BenParizek** [comment]
This feature is importing data correctly, however appears to be a bug in Craft in how the data is retrieved which can cause the versions to display in an incorrect order: https://github.com/craftcms/cms/issues/2889

**Comment by colinmeinke** [comment]
This works great!! Thanks @BenParizek @pdaleramirez ✌️
