### ISSUE TITLE
Updating matrix not respecting site

### ISSUE THREAD

**Issue by colinmeinke** [barrelstrength/craft-sprout-import#28]
I have a section that has a matrix field, where the block fields are translatable, but the blocks are **not** managed on a per site basis.

When I update an entry where `settings.updateElement.matchCriteria.siteId` is set to specific site, the matrix fields are updated for **all** sites, not just the defined site as I would expect. 

I can get around this by turning on `Manage blocks on a per-site basis`, but I don't think this should be a requirement.

**Comment by BenParizek** [comment]
Can you confirm the Translation setting you are using for your Matrix field? Are they set to`Not translatable`?

We may need to confirm if this is expected behavior from Craft. I don't know the exact conditions but I do believe Craft stores multiple records to the database for different Sites depending on the settings.

**Comment by colinmeinke** [comment]
To recreate:

1. Leave the matrix field setting `Manage blocks on a per-site basis` unchecked.
2. Create a single block type where the contained fields are set to "Translate for each site"/"Manage relations on a per-site basis".

Craft admin UI behaviour:

- When a block is added/deleted it applies to all sites.
- Editing a specific field in a block will only apply to the site that is being edited.

The last part is where Sprout doesn't match the UI behaviour, and instead applies edits to all sites.

**Comment by pdaleramirez** [comment]
@BenParizek I don't think this is a bug but a feature where you can modify the field settings on import.

**Comment by colinmeinke** [comment]
@pdaleramirez I'd classify it as a bug, as it does not match the behaviour of the Craft admin UI. Why would field settings need to be modified on import?

**Comment by BenParizek** [comment]
Sprout Import has been discontinued and we won't be adding any additional multi-site support. Please see FeedMe for first-party import support.
