### ISSUE TITLE
Importing multiple entry relationships based on custom field - Undefined offset

### ISSUE THREAD

**Issue by colinmeinke** [barrelstrength/craft-sprout-import#29]
I am trying to create a relationship to another section, based on a custom field.

```
[
  {
    "@model": "barrelstrength\\sproutimport\\integrations\\sproutimport\\elements\\Entry",
    "attributes": {
      "authorId": 1
    },
    "content": {
      "related": {
        "headerMenu": {
          "@model": "barrelstrength\\sproutimport\\integrations\\sproutimport\\elements\\Entry",
          "matchBy": "legacyId",
          "matchValue": [
            749,748,751,911,922,839,903
          ]
        }
      }
    },
    "settings": {
      "updateElement": {
        "matchBy": "slug",
        "matchValue": "header",
        "matchCriteria": {
          "siteId": 2
        }
      }
    }
  }
]
```

This isn't working even though the values do exist for `legacyId`. Any ideas as to why? I cannot work out what I'm doing wrong here.

I've also tried adding `content.related.headerMenu.matchCriteria.sectionId`, with no luck.

**Comment by colinmeinke** [comment]
The error that appears throughout the `queue.log` is `Undefined offset: 0`. I have manually checked that the target entries all exist and have the correct `legacyId` values.

**Comment by pdaleramirez** [comment]
@colinmeinke is legacyId a plainText custom field or an entries field. What are those values in matchValue are those craft entry ids or manually inputted from other database?

**Comment by pdaleramirez** [comment]
legacyId should just match a number not an array.
```
          "matchBy": "legacyId",
          "matchValue": 749
```
For custom fields you can only match it as number or string. Array only works when matching an Entry by the Element's attributes such as id and slug.

**Comment by colinmeinke** [comment]
I guess this is an enhancement, rather than a question from what you've said.

**Comment by pdaleramirez** [comment]
You will have to refactor the way you generate the json data. You can collect all entries that matches the legacyId and have it return as their entry ids, So you will have
```
"matchBy": "id",
"matchValue": [12, 13, 14]
```
Where 12, 13 and 14 are entry ids instead of legacyIds

**Comment by colinmeinke** [comment]
Yep, that would require me to write a script that does that lookup. It also means instead of importing all my data in one or two batches, I have to then run that script half way through the import. All in all not that convenient, as I want to run the migration process at regular intervals. Please see this as a feature request.

**Comment by colinmeinke** [comment]
I spent the time writing a script to convert `legacyId` to element id and I _still_ get `Undefined offset: 0` error on import. Am I doing something wrong here?

```
"headerMenu": {
  "@model": "barrelstrength\\sproutimport\\integrations\\sproutimport\\elements\\Entry",
  "matchBy": "id",
  "matchValue": [6396,6543,6375,6354,6347,6480,6620],
  "matchCriteria": { "sectionId": 18 }
}
```

**Comment by pdaleramirez** [comment]
@colinmeinke I could not re-produce this issue. I will debug it personally.

**Comment by colinmeinke** [comment]
@pdaleramirez hmm. That's odd. The query my script is doing to retrieve IDs is `SELECT * FROM content WHERE field_legacyId=${legacyId}` and then using `elementId` from the first result. I **think** elementId is the same as the entry id?

**Comment by colinmeinke** [comment]
It doesn't seem to be a problem with not finding the id though, more that it's not expecting an array.

**Comment by BenParizek** [comment]
@colinmeinke fyi, I've just added a comment to another, a related ticket that may better explain why the array syntax is failing in your first use case. See here for more info: https://github.com/barrelstrength/craft-sprout-import/issues/39#issuecomment-390862042

I'll leave this ticket open until we get your `Undefined offset` question above resolved.

**Comment by colinmeinke** [comment]
@BenParizek cool, this doesn't explain why I get the same error when switching it out for entry ids though.

**Comment by colinmeinke** [comment]
Not working with `id` was my error. I needed to add it to the `related` object, not `fields`. I will close this in favor of https://github.com/barrelstrength/craft-sprout-import/issues/39
