### ISSUE TITLE
dateUpdated and dateCreated have no effect

### ISSUE THREAD

**Issue by colinmeinke** [barrelstrength/craft-sprout-import#30]
`attributes.dateCreated` and `attributes.dateUpdated` don't have any effect when importing a new entry. However, `attributes.postDate` does work as expected. When viewing the newly created entry `Created at:` and `Updated at:` both show the datetime of import, not the datetimes defined in the json.

**Comment by pdaleramirez** [comment]
@BenParizek Craft does not support this yet. I submitted an issue about this here https://github.com/craftcms/cms/issues/2909

**Comment by BenParizek** [comment]
Based on Brandon's comment:

> Those are meant to be more like audit attributes that our base ActiveRecord class sets automatically (and doesn’t even give the outside code a choice on their values), so this isn’t something we could change without making a pretty significant change to ActiveRecord behavior.

We'll consider this expected functionality and won't be adding support for this in Sprout Import. If `dateUpdated` or `dateCreated` need to be modified, the best approach is to handle those updates with a separate script.

**Comment by BenParizek** [comment]
Feature Request issue added here: https://github.com/barrelstrength/craft-sprout-import/issues/54
