### ISSUE TITLE
Import user photo

### ISSUE THREAD

**Issue by colinmeinke** [barrelstrength/craft-sprout-import#31]
I am importing users, which works well until I try to import their photo.

```
"photo": {
  "@model": "barrelstrength\\sproutimport\\integrations\\sproutimport\\elements\\Asset",
  "matchBy": "filename",
  "matchValue": [ "photo_14.jpg" ],
  "matchCriteria": {
    "folderId": 15
  }
}
```

Added to `attributes` this throws an error, along the lines of `setPhoto() was expecting an Asset, but received an array`.

Adding to `content.related` this is just silently ignored.

How would I go about importing a user photo?

**Comment by colinmeinke** [comment]
@BenParizek @pdaleramirez any thoughts on this one? This is the only issue we're waiting on an answer on, before we do a final migration.

**Comment by pdaleramirez** [comment]
That should work if the image is on the Craft Asset. Try removing `folderId` maybe it is in the wrong folder.

**Comment by colinmeinke** [comment]
@pdaleramirez ohh perfect, thanks!

**Comment by BenParizek** [comment]
@colinmeinke This is now supported in the latest release. The syntax is a bit different than what was proposed above. For examples see:

- [Related Attributes](https://sprout.barrelstrengthdesign.com/docs/import/related-attributes.html#users)

```
[
  {
    "@model": "barrelstrength\\sproutimport\\importers\\elements\\User",
    "attributes": {
      "username": "beryl01",
      "firstName": "Luigi",
      "lastName": "Bednar",
      "email": "muller.giuseppe@howell.com",
      "pending": 1,
      "lastLoginDate": "2014-12-11 04:12:06",
      "dateCreated": "2014-04-09 12:04:04",
      "dateUpdated": "2015-04-04 06:04:08",
      "related": {
        "photoId": {
          "@model": "barrelstrength\\sproutimport\\importers\\elements\\Asset",
          "params": {
            "filename": "headshot.jpg",
            "volumeId": 1
          }
        }
      }
    }
  }
]
```
