### ISSUE TITLE
Section and Field importing may not play nice with Seed generation

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/craft-sprout-import#32]
There may be a bug in how we import Sections and Fields. I imported the Section-All-Fields script and then tried to generate fake entries and I got errors that it couldn't find the specific fields that were imported to that new Section. I went and resaved the Section and this fixed the issue.

It seems that somehow in the import process when getAllFieldHandles calls getFieldsByElementType, the wrong list gets returned. And the right field list gets returned after the section is resaved.

**Comment by pdaleramirez** [comment]
I could not recreate this issue. Imported the example Section-All-Field.json and seed the created testSection. I did not encounter any error.
