### ISSUE TITLE
Installation breaks craft console (Invalid path alias)

### ISSUE THREAD

**Issue by timkelty** [barrelstrength/craft-sprout-import#34]
```Exception 'yii\base\InvalidArgumentException' with message 'Invalid path alias: @barrelstrength/sproutbase/controllers'``

`1.0.0-beta.7`

**Comment by BenParizek** [comment]
@timkelty Can you update to `1.0.0-beta.10`. We just released it today and it should resolve this issue.

You'll want to use the 'Update All' option if you have more than one Sprout plugin installed as several things have changed in the application structure.

**Comment by timkelty** [comment]
Like a charm!
