### ISSUE TITLE
Setting unknown property: craft\elements\db\AssetQuery::sourceId

### ISSUE THREAD

**Issue by alexmglover** [barrelstrength/craft-sprout-import#37]
### Description
Attempting to seed and am getting this error:

`Setting unknown property: craft\elements\db\AssetQuery::sourceId`

### Steps to reproduce

1. Create a channel with an assets field.
2. Attempt to seed 100 entries into this channel, get a failed error message.

### Additional info

- Craft version: 3.0.8
- PHP version: 7.1.16
- Database driver & version: 5.6.40
- Plugins & versions: Sprout Import 1.0.0-beta.10

### Supporting assets

- [ ] [16428819010](https://app.intercom.io/a/apps/dfa024eb83c11784227312bba407fb3d35e00fa7/inbox/inbox/714050/conversations/16428819010)

**Comment by alexmglover** [comment]
I should probably say that the assets are being stored on S3, and I am not sure if that is possibly the cause of this issue.

**Comment by BenParizek** [comment]
@alexmglover So far, I'm unable to recreate this issue. I did discover a small asset seed bug and pushed a fix in Sprout Import 1.0.0-beta.11, however, I'm not sure it's related.

Can you update to the latest and test again? While I love the Seed 100 entries path, might be better to test with just a couple seed entries to rule out any memory issues or other outlier cases that could be happening. 

Let me know how it goes, and if you're still running into issues, if you could provide more data or share your database with us at sprout@barrelstrengthdesign.com we can dig in further.

**Comment by alexmglover** [comment]
Thanks, I sent you an email. Lowering the number of seeded entries did not
do the trick.

**Comment by BenParizek** [comment]
@alexmglover We've looked into this and are not seeing any related issue in our code. We think the issue may be that the example in our docs that you might have referenced is using Craft 2 properties.

[sourceId](https://docs.craftcms.com/api/v3/craft-elements-db-assetquery.html#method-sourceid) has been deprecated and replaced by [volumeId](https://docs.craftcms.com/api/v3/craft-elements-db-assetquery.html#property-volumeid).

Let me know if that helps get things resolved.

**Comment by alexmglover** [comment]
For the example I sent, I installed Craft 3, installed Sprout Import from the plugin store, added a few fields and then tried to run the seeder. I didn’t add anything manually to attempt to seed, so I’m not sure what example you are referring to.

**Comment by BenParizek** [comment]
@alexmglover My mistake, I got tripped up on what I thought the problem was. Thanks for the example and this was an issue on our end.

I just pushed a fix in `v1.0.0-beta.12`, now available in the plugin store if you'd like to kick the tires.

**Comment by alexmglover** [comment]
Great! Thank you so much!
