### ISSUE TITLE
Remove matchBy and related legacy match references in Entry::generateEntry integration

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/craft-sprout-import#48]
Should use params instead and deprecate matchBy here:
https://github.com/barrelstrength/craft-sprout-import/blob/v1/src/importers/elements/Entry.php#L155

**Comment by pdaleramirez** [comment]
@BenParizek there is no related setting on generateEntry but on other function still supported as well as the params settings,

**Comment by pdaleramirez** [comment]
@BenParizek I have removed the entryParams code that has matchBy and matchValue reference because it seems that it is not used anymore in seeding entries.
