### ISSUE TITLE
Problems with dateCreated and dateUpdated when importing users

### ISSUE THREAD

**Issue by oadslug** [barrelstrength/craft-sprout-import#53]
### Description

I can't seem to import `dateCreated` or `dateUpdated` when importing users — it always reverts to the current datetime.

I've tried the compact version:

    "dateCreated": "2017-01-16 03:47:23",

And the more lengthy version that I have seen in various doc examples:

     "dateCreated": {
            "date": "1/16/2017",
            "time": "3:47 PM"
      },

### Additional info

- Craft version: Craft CMS 3.0.12
- PHP version: 7.0.13
- Database driver & version: MySQL 5.6.34
- Plugins & versions: Sprout Import 1.0.0-beta.13

**Comment by oadslug** [comment]
I sort of understand the reasoning — just don't particularly agree. On most project wouldn't matter, but in this case, they have 10+ years of customers (19,000+). Knowing how long they have been a customer is extremely valuable. And I know that I can add another field to store this data, but that seems silly. Not to mention the fact that you can't sort list view on custom fields without writing some additional logic. Imho should just let us set it to whatever we want — the craft way! :)

**Comment by BenParizek** [comment]
Thanks @oadslug. I'll mark this as a feature request and we'll consider some options when we have a chance. 

Yeah, unfortunately, this isn't the Craft way right now so we'll need to explore alternate ways to support it. Thanks for calling out the issue in the docs. We'll get that cleaned up and try to clarify the behavior better.

**Comment by BenParizek** [comment]
Feature Request issue added here: https://github.com/barrelstrength/craft-sprout-import/issues/54
