### ISSUE TITLE
Composer dependency conflict with Sprout-Fields?

### ISSUE THREAD

**Issue by brettgullan** [barrelstrength/craft-sprout-import#56]
### Description

I have a Craft 3.0.17.1 install, with Sprout-Fields 3.1.5 installed.
When I attempt to install Sprout-Import I get the following Composer error:

```
Problem 1
    - Installation request for barrelstrength/sprout-import 1.0.0-beta.13 -> satisfiable by barrelstrength/sprout-import[1.0.0-beta.13].
    - barrelstrength/sprout-fields 3.1.5 requires barrelstrength/sprout-base ^3.0.0 -> satisfiable by barrelstrength/sprout-base[3.0.0].
    - barrelstrength/sprout-fields 3.1.5 requires barrelstrength/sprout-base ^3.0.0 -> satisfiable by barrelstrength/sprout-base[3.0.0].
    - barrelstrength/sprout-fields 3.1.5 requires barrelstrength/sprout-base ^3.0.0 -> satisfiable by barrelstrength/sprout-base[3.0.0].
    - Conclusion: don't install barrelstrength/sprout-base 3.0.0
    - Installation request for barrelstrength/sprout-fields 3.1.5 -> satisfiable by barrelstrength/sprout-fields[3.1.5].
```

The error is the same, regardless of whether I attempt to install Sprout Import via Plugin Store, or via Composer CLI.

Is there a way around this, or does it need a version bump in Sprout Import's composer.json?

**Comment by brettgullan** [comment]
Hi @BenParizek,

I tried removing my `vendor` directory and re-running `composer install` and got the same error message.

Copy of my composer.json file attached.

Thanks!

[composer.json.zip](https://github.com/barrelstrength/craft-sprout-import/files/2243723/composer.json.zip)

**Comment by brettgullan** [comment]
UPDATE …

So, I managed to get it working, by first removing the `barrelstrength/sprout-fields` entry from my `composer.json` file, then running `composer install`, followed by `composer require barrelstrength/sprout-fields`.

This installs sprout-import `1.0.0-beta.13` and sprout fields `3.1.4`.

The Craft Updates utility lists sprout fields `3.1.5` as available. But if I try to install it, I get the same error.

**Comment by BenParizek** [comment]
@brettgullan Thanks for the update. We'll explore a bit more and see what we find.

**Comment by BenParizek** [comment]
@brettgullan I just pushed Sprout Import v1.0.0-beta.14 up to the plugin store which should resolve this. Let me know if you continue to run into anything.
