### ISSUE TITLE
Example Import for Commerce Products doesn't work

### ISSUE THREAD

**Issue by hendrikeng** [barrelstrength/craft-sprout-import#63]
### Description
Trying to import the example Json Import for craft commerce products fails

### Steps to reproduce

1. import the snippet from the docs
2. 

### Additional info
- Craft Commerce; 2.0.0-beta.8.1
- Craft version: 3.0.0-RC10
- PHP version: 7.2
- Database driver & version: mysql  Ver 15.1 Distrib 10.2.14-MariaDB, for osx10.13 (x86_64) using readline 5.1
- Plugins & versions: v1.0.0-beta.14

**Comment by BenParizek** [comment]
@hendrikeng Can you update to the latest version of Craft, test again, and share the specific error you're getting? Do you happen to have a multi-Site Craft install?

**Comment by hendrikeng** [comment]
@BenParizek I updated everything to the last versions and run the import again, the error from the que.log is:

´´´
2018-09-08 16:08:43 [-][-][-][error][sprout-import] Unable to run Sprout Import job.
2018-09-08 16:08:43 [-][-][-][error][sprout-import] SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'orderLanguage' cannot be null
The SQL being executed was: INSERT INTO `commerce_orders` (`id`, `number`, `itemTotal`, `email`, `isCompleted`, `dateOrdered`, `datePaid`, `shippingMethodHandle`, `paymentSourceId`, `gatewayId`, `orderStatusId`, `couponCode`, `totalPrice`, `totalPaid`, `currency`, `lastIp`, `orderLanguage`, `paymentCurrency`, `customerId`, `returnUrl`, `cancelUrl`, `message`, `paidStatus`, `dateCreated`, `uid`, `dateUpdated`) VALUES (10567, 'fcfb9fb3b6e700c85285cc1de018ce80', '0', '', 0, NULL, NULL, NULL, NULL, NULL, 1, NULL, '0', '0', NULL, NULL, NULL, 'CHF', NULL, NULL, NULL, NULL, 'unpaid', '2018-09-08 14:08:43', 'd32715a3-ba49-4c30-b7fa-4e93f5ed1fce', '2018-09-08 14:08:43')
2018-09-08 16:08:43 [-][-][-][error][craft\queue\QueueLogBehavior::afterError]  [1] Importing Data. (attempt: 1) - Error (time: 0.236s): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'orderLanguage' cannot be null
The SQL being executed was: INSERT INTO `commerce_orders` (`id`, `number`, `itemTotal`, `email`, `isCompleted`, `dateOrdered`, `datePaid`, `shippingMethodHandle`, `paymentSourceId`, `gatewayId`, `orderStatusId`, `couponCode`, `totalPrice`, `totalPaid`, `currency`, `lastIp`, `orderLanguage`, `paymentCurrency`, `customerId`, `returnUrl`, `cancelUrl`, `message`, `paidStatus`, `dateCreated`, `uid`, `dateUpdated`) VALUES (10567, 'fcfb9fb3b6e700c85285cc1de018ce80', '0', '', 0, NULL, NULL, NULL, NULL, NULL, 1, NULL, '0', '0', NULL, NULL, NULL, 'CHF', NULL, NULL, NULL, NULL, 'unpaid', '2018-09-08 14:08:43', 'd32715a3-ba49-4c30-b7fa-4e93f5ed1fce', '2018-09-08 14:08:43')
2018-09-08 16:08:43 [-][-][-][error][yii\db\IntegrityException] PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'orderLanguage' cannot be null in /Users/hendrik/Documents/Github/Projects/wfw/vendor/yiisoft/yii2/db/Command.php:1258
´´´

Thanks a lot Ben

**Comment by pdaleramirez** [comment]
I fixed this bug and it now requires to have the` "orderLanguage": "en-US"` attribute.

**Comment by BenParizek** [comment]
@pdaleramirez We may need another way to handle the fallback customer logic in this commit or perhaps we just need to throw an error if a customer is required and not provided.

`Plugin::getInstance()->getCustomers()->getCustomer()` calls `Craft::$app->getSession();` so it will cause issues if the scenario is encountered via a console command.

**Comment by BenParizek** [comment]
This example has been updated in the docs.
