### ISSUE TITLE
Order Importer not being loaded?

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/craft-sprout-import#66]
It appears Sprout Import may not be registering the Order Element Importer. It appears to register Products when Commerce is installed. Imported classes here:
barrelstrength\sproutbase\app\import\services\Importers

**Comment by pdaleramirez** [comment]
This gets fixed in this pull request merge here https://github.com/barrelstrength/craft-sprout-import/commit/fc5a56715a07e4ccaf052b834ab34ea792329069
currently in develop branch

**Comment by BenParizek** [comment]
We seem to only be loading the Product Class:

```
if (Craft::$app->getPlugins()->getPlugin('commerce')) {
            $importerTypes[] = Products::class;
        }```
