### ISSUE TITLE
newElements parameter causes countable bug - PHP 7.2

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/craft-sprout-import#67]
A user had to set to set createIfNotFound to false the create new items and set an empty array on the newElements Param because otherwise it kept trying to count(NULL).

	'createIfNotFound' => false,
	'newElements' => []

http://share.barrelstrength.co/0Q1J2c3j2a3h

### Notify

- [x] Robert Tolton on Slack

**Comment by pdaleramirez** [comment]
This already has been fixed on this merge request https://github.com/barrelstrength/craft-sprout-import/commit/fc5a56715a07e4ccaf052b834ab34ea792329069
Fixed on version **v1.0.0-beta.15**
