### ISSUE TITLE
Add support for Asset folderPath Property

### ISSUE THREAD

**Issue by andrelopez** [barrelstrength/craft-sprout-import#69]
We will consider supporting this feature in the future but it may require some refactoring.

----

More info: https://craftcms.stackexchange.com/questions/27956/sprout-import-doesnt-recognize-asset-folderpath-property

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_e7oj)

**Comment by pdaleramirez** [comment]
I have answered the issue here https://craftcms.stackexchange.com/questions/27956/sprout-import-doesnt-recognize-asset-folderpath-property/28097#28097
