### ISSUE TITLE
Orders are documented but don't appear to ever get loaded

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/craft-sprout-import#73]
Documentation:
https://sprout.barrelstrengthdesign.com/docs/import/orders.html

Only Products are loaded if Commerce is installed:
https://github.com/barrelstrength/craft-sprout-base/blob/v4/src/app/import/services/Importers.php#L107

Let's confirm the Orders example works as expected and get Orders loading properly.

Also see comment here:
<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_f1bn)

### Notify

- [ ] Jessie Gilligan on Craft Slack

**Comment by rattikarl** [comment]
I think this one here https://github.com/barrelstrength/craft-sprout-import/commit/c5fe1cd1cce5ee5c6efeebf884b40f80875a4bf4 was the last commit when order imports were working for me

**Comment by rattikarl** [comment]
Works fine again ( with your latest release https://github.com/barrelstrength/craft-sprout-import/commit/2cb64a4d16397766eb31ae429d624cd778bc837a )
However some fields from your order example aren't imported. 
Following fields stay empty:

"countryCode": "GB",
"address1": "45 Fam Road",
"city": "Partu",

**Comment by pdaleramirez** [comment]
@BenParizek The Order Element importing is working. The reference you posted which is this https://github.com/barrelstrength/craft-sprout-base/blob/v4/src/app/import/services/Importers.php#L107
is only for Field Importers. We do not need any Field Order importer. @rattikarl can you try the latest version and let us know here if it's working

**Comment by rattikarl** [comment]
Import works fine with v1.0.0-beta.18 https://github.com/barrelstrength/craft-sprout-import/commit/2cb64a4d16397766eb31ae429d624cd778bc837a
only 'qty' isn't imported correctly. Whatever value I enter here, it always switches to '1' in craftcommerce.  @pdaleramirez

**Comment by pdaleramirez** [comment]
@rattikarl I was not able to reproduce the qty issue. It is working on the **v1.0.0-beta.18**.

**Comment by wewereyoung** [comment]
@pdaleramirez Sounds good, I'll try again with a fresh install

**Comment by rattikarl** [comment]
Tried it with a completely fresh Craft+CraftCommerce+ Sprout Import Plugin install and keep getting
this error now

```
2018-11-16 08:42:41 [-][1][-][info][yii\db\Command::execute] UPDATE `queue` SET `fail`=1, `dateFailed`='2018-11-16 16:42:41', `error`='session_set_cookie_params(): Cannot change session cookie parameters when headers already sent' WHERE `id`='3'
2018-11-16 08:42:41 [-][1][-][profile begin][yii\db\Command::execute] UPDATE `queue` SET `fail`=1, `dateFailed`='2018-11-16 16:42:41', `error`='session_set_cookie_params(): Cannot change session cookie parameters when headers already sent' WHERE `id`='3'
2018-11-16 08:42:41 [-][1][-][profile end][yii\db\Command::execute] UPDATE `queue` SET `fail`=1, `dateFailed`='2018-11-16 16:42:41', `error`='session_set_cookie_params(): Cannot change session cookie parameters when headers already sent' WHERE `id`='3'
2018-11-16 08:42:41 [-][1][-][info][yii\db\Command::query] SELECT *
FROM `queue`
WHERE ((`fail`=FALSE) AND (`timeUpdated` IS NULL)) AND (`timePushed` <= 1542386561 - `delay`)
ORDER BY `priority`, `id`
LIMIT 1
2018-11-16 08:42:41 [-][1][-][profile begin][yii\db\Command::query] SELECT *
FROM `queue`
WHERE ((`fail`=FALSE) AND (`timeUpdated` IS NULL)) AND (`timePushed` <= 1542386561 - `delay`)
ORDER BY `priority`, `id`
LIMIT 1
2018-11-16 08:42:41 [-][1][-][profile end][yii\db\Command::query] SELECT *
FROM `queue`
WHERE ((`fail`=FALSE) AND (`timeUpdated` IS NULL)) AND (`timePushed` <= 1542386561 - `delay`)
ORDER BY `priority`, `id`
LIMIT 1
```

**Comment by BenParizek** [comment]
@rattikarl Can you create a new issue or send a note to sprout@barrelstrengthdesign.com with a complete example of the code you are using for the import? This thread was initially about getting things working in general and now it seems like we have a more specific issue to figure out around a particular type of data.
