### ISSUE TITLE
Importing Commerce Orders won't work

### ISSUE THREAD

**Issue by rattikarl** [barrelstrength/craft-sprout-import#74]
### Description
Tried to import orders with a fresh craft commerce install.
Used your sample json for testing just changing user and skus to existing parameters.

```
[
  {
    "@model": "barrelstrength\\sproutbase\\app\\import\\importers\\elements\\Order",
    "attributes": {
      "currency": "USD",
      "billingAddressId": null,
      "shippingAddressId": null,
      "shippingMethodHandle": "freeShipping",
      "gatewayId": 1,
      "customerId": "hi@wewereyoung.de",
      "orderStatusId": 1,
      "orderLanguage": "en-US",
      "isCompleted": 1,
      "dateOrdered": "2016-05-21 01:08:38",
      "datePaid": "2016-05-21 01:09:38",
      "returnUrl": "/commerce/customer/order?number={number}",
      "cancelUrl": "/commerce/checkout/payment"
    },
    "content": {
      "title": "Order One",
      "fields": []
    },
    "lineItems": [
      {
        "sku": "ANT-001",
        "qty": "3",
        "options": []
      },
      {
        "sku": "TFA-001",
        "qty": "1",
        "options": []
      }
    ],
    "payments": {
      "firstName": "Boy",
      "lastName": "Sue",
      "number": "4929000000006",
      "month": "1",
      "year": "2020",
      "cvv": "123"
    },
    "transactions": {
      "status": "success",
      "reference": "ch_XXXXXX",
      "response": "{\"cardType\":\"visa\",\"cardExpiryMonth\":\"03\",\"cardExpiryYear\":\"2021\",\"gateway\":\"stripe\"}"
    },
    "addresses": {
      "billingAddress": {
        "firstName": "Boy",
        "lastName": "Sue",
        "countryCode": "GB",
        "state": "",
        "address1": "45 Fam Road",
        "city": "Partu",
        "zipCode": "NBH BNY"
      }
    }
  }
]
```

it fails with following errors:

https://gist.github.com/rattikarl/0f0a167b3d71f2444ed9abf8c0e6c533

### Steps to reproduce

1. Took Sample import from Website and changed SKUs to existing ones
2. Clicked on Import and checked logs after it failed

### Additional info

- Craft version: 3.0.31
- PHP version: 7.2.12
- Database driver & version: MySQL 5.7.24
- Plugin Version:
Craft Commerce | 2.0.0-beta.13.1
Sprout Import | 1.0.0-beta.18

no other plugins installed

**Comment by rattikarl** [comment]
If i install  "ostark/craft-async-queue" plugin: "^1.3.0", via composer I do not get this error anymore. Order imports work that way. only quantity is not imported correctly it always switches to 1 no matter what I enter in the import.json

**Comment by pdaleramirez** [comment]
@BenParizek 
There is an issue on craft commerce on importing order element through jobs queue. I submitted an issue about this and seems that it still has not resolve. I  updated the issue and mention luke about this.
Submitted issue here https://github.com/craftcms/commerce/issues/375

**Comment by BenParizek** [comment]
Sprout Import has been discontinued and we won't be adding any further support for Commerce Orders.
