### ISSUE TITLE
Ignores JSON Errors on Multiple Import Files

### ISSUE THREAD

**Issue by kgrote** [barrelstrength/craft-sprout-import#77]
### Description
When importing more than one JSON file at a time, Sprout Import will not report if there are JSON errors in any files beyond the first one. So the import will appear to run without errors but the import files will not be run.

### Steps to reproduce

1. Upload 2 or more JSON files for import, the second one containing JSON errors
2. Run the import.
3. Sprout Import will run the import process for the first file without errors, then bail out without errors for the remaining files.

### Additional info

- Craft version: 3.1.1
- PHP version: 7.1.12
- Database driver & version: MySQL 5.6.38

**Comment by pdaleramirez** [comment]
This commit fixes this issue https://github.com/barrelstrength/craft-sprout-base/commit/3e748db1fcf5776ab62655caba3636786041c2a4

@BenParizek I will have this merge also when we separate sprout-base-import
Tests:
2 files - 1st file valid - 2nd file invalid = Displays 2nd file error json and imports first file successfully
2 files - 1st file invalid - 2nd file valid = Display 1st file error json and imports 2nd file successfully
5 files - 2 invalid files = Display invalid files error json and imports valid file successfully

**Comment by BenParizek** [comment]
@kgrote This issue has been addressed in the latest release: v1.0.0-beta.21
