### ISSUE TITLE
Class 'barrelstrength\sproutbase\app\import\services\Themes' not found

### ISSUE THREAD

**Issue by hegrobler** [barrelstrength/craft-sprout-import#79]
### Description
I was doing what I thought would be a routine update via the Cpanel but am receiving the following error: **Class 'barrelstrength\sproutbase\app\import\services\Themes' not found**
I've never run into this type of error and have no idea how to proceed.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_hv63)

**Comment by BenParizek** [comment]
@hegrobler 

Can you share more about what version of Craft and any other Sprout plugins you are using? I do recognize that bug from a while ago but I thought that we had resolved it a while ago as well. The error message uses a path to a class that no longer exists in our plugins, so I believe this may involve an older version somehow.

Can you revert to your old db and try to upgrade Craft to the latest and then update Sprout again after you update Craft to the latest? Craft did introduce some breakpoints recently around the Craft 3.1 release so (I'm guessing) but it's possible that if you try to update a certain Sprout plugin with a lower version of Craft it may not get upgraded to the latest somehow.

Anything more you can share about the versions and steps you are taking to recreate this would be helpful.

**Comment by BenParizek** [comment]
This issue has been resolved in a separate email thread.

**Comment by billymedia** [comment]
I have also encountered this issue, you mentioned that you resolved this, what did you have to do? @BenParizek

**Comment by BenParizek** [comment]
@billymedia We retired Sprout Import a couple of years ago now after Pixel & Tonic purchased the FeedMe plugin and made it first-party. I recommend using FeedMe moving forward.
