### ISSUE TITLE
Using sectionId and typeId

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/craft-sprout-import#80]
<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_iaz7)

**Comment by pdaleramirez** [comment]
@BenParizek i have fixed this bug here https://github.com/barrelstrength/craft-sprout-base-import/commit/0cf6529e63da463f56f0b4ec9e6d43f4dfcf42b7 

This fixed bug on Setting attribute relation the caused is the count() method and if it returns a integer it does not pass the condition
