### ISSUE TITLE
wrong version of sprout-base

### ISSUE THREAD

**Issue by cornernote** [barrelstrength/craft-sprout-import#84]
PHP Fatal Error 'yii\base\ErrorException' with message 'Trait 'barrelstrength\sproutbase\base\BaseSproutTrait' not found' in /app/vendor/barrelstrength/sprout-base-import/src/SproutBaseImport.php:29

The composer.json shows the module requesting sprout-base v5:

https://github.com/barrelstrength/craft-sprout-import/blob/v1/composer.json#L30

```
        "barrelstrength/sprout-base": "^5.0.0",
```

The module tries to use `BaseSproutTrait`, which it seems is a sprout-base v4 class:
https://github.com/barrelstrength/craft-sprout-import/blob/v1/src/SproutImport.php#L36

https://github.com/barrelstrength/craft-sprout-base/tree/v4/src/base
 - BaseSproutTrait.php exists

https://github.com/barrelstrength/craft-sprout-base/tree/v5/src/base
 - BaseSproutTrait.php does not exist

The same issue exists here:

https://github.com/barrelstrength/craft-sprout-base-import/blob/v1/src/SproutBaseImport.php#L29

### Additional info

- Craft version: 3.4.20
- PHP version: 7.2.3

**Comment by BenParizek** [comment]
@cornernote As stated on the plugin page and in the README, we've discontinued support of Sprout Import, for some time now. We recommend using the first party FeedMe as an alternative.

If you want to try your luck with using Sprout Import, feel free to do so but we don't have the bandwidth to offer support outside of a support contract.
