### ISSUE TITLE
Fails to install

### ISSUE THREAD

**Issue by joomkit** [barrelstrength/craft-sprout-import#85]
### Description (screenshots, logs, ...)

A fatal error has occurred:

Status: error

Response: <pre>PHP Fatal Error &#039;yii\base\ErrorException&#039; with message &#039;Trait &#039;barrelstrength\sproutbase\base\BaseSproutTrait&#039; not found&#039;

in /home/staging/craft/vendor/barrelstrength/sprout-import/src/SproutImport.php:36

Stack trace:
#0 [internal function]: yii\base\ErrorHandler-&gt;handleFatalError()
#1 {main}</pre>

### Steps to reproduce

1. install via plugin store

### Additional info

- Craft version: latest 3.5.18
- PHP version: 7.3

**Comment by BenParizek** [comment]
Sorry @joomkit, Sprout Import is no longer supported. I recommend checking out the first-party Feed Me plugin as an alternative.
