### ISSUE TITLE
Dependancy issue

### ISSUE THREAD

**Issue by anchovy** [barrelstrength/craft-sprout-import#86]
### Description (screenshots, logs, ...)

I've got sprout-redirects installed (pro version) and need to instalsprout-import (`composer require barrelstrength/sprout-import`) to do bulk imports but I'm getting a dependency issue because sprout-redirects requires sprout base ^6.0.0 but sprout-import requires ^5.0.0;

```

Problem 1
    - Conclusion: don't install barrelstrength/sprout-import 1.0.2
    - Conclusion: don't install barrelstrength/sprout-import 1.0.1
    - Conclusion: remove barrelstrength/sprout-base 6.0.2
    - Installation request for barrelstrength/sprout-import ^1.0 -> satisfiable by barrelstrength/sprout-import[1.0.0, 1.0.1, 1.0.2].
    - Conclusion: don't install barrelstrength/sprout-base 6.0.2
    - barrelstrength/sprout-import 1.0.0 requires barrelstrength/sprout-base ^5.0.0 -> satisfiable by barrelstrength/sprout-base[5.0.0, 5.0.1, 5.0.2, 5.0.3, 5.0.4, 5.0.5, 5.0.7, 5.0.9, 5.1.0, 5.1.1, 5.1.2, 5.1.3, 5.2.0].
    - Can only install one of: barrelstrength/sprout-base[5.0.0, 6.0.2].
    - Can only install one of: barrelstrength/sprout-base[5.0.1, 6.0.2].
    - Can only install one of: barrelstrength/sprout-base[5.0.2, 6.0.2].
    - Can only install one of: barrelstrength/sprout-base[5.0.3, 6.0.2].
    - Can only install one of: barrelstrength/sprout-base[5.0.4, 6.0.2].
    - Can only install one of: barrelstrength/sprout-base[5.0.5, 6.0.2].
    - Can only install one of: barrelstrength/sprout-base[5.0.7, 6.0.2].
    - Can only install one of: barrelstrength/sprout-base[5.0.9, 6.0.2].
    - Can only install one of: barrelstrength/sprout-base[5.1.0, 6.0.2].
    - Can only install one of: barrelstrength/sprout-base[5.1.1, 6.0.2].
    - Can only install one of: barrelstrength/sprout-base[5.1.2, 6.0.2].
    - Can only install one of: barrelstrength/sprout-base[5.1.3, 6.0.2].
    - Can only install one of: barrelstrength/sprout-base[5.2.0, 6.0.2].
    - Installation request for barrelstrength/sprout-base (locked at 6.0.2) -> satisfiable by barrelstrength/sprout-base[6.0.2].

```

### Steps to reproduce

1. install sprout-redirect, which also includes the following dependencies:

```
    "require": {
        "craftcms/cms": "^3.4.0",
        "barrelstrength/sprout-base": "^6.0.0",
        "barrelstrength/sprout-base-redirects": "^1.5.4"
    },
```

2. Try installing composer require barrelstrength/sprout-import

### Additional info

- Craft version: Craft Pro 3.6.15
- PHP version: 7.4.16
- Database driver & version:  MySQL 5.7.32
- Plugins & versions:
Sprout Encode Email: 2.0.7
Sprout Redirects: 1.5.3

Modules:
sprout | barrelstrength\sproutbase\SproutBase
barrelstrength\sproutbaseredirects\SproutBaseRedirects

@sproutbase
@sproutbaseicons
@sproutbaseredirects
@sproutredirects

_For some issues, we may request that you send the following items to Support <sprout@barrelstrengthdesign.com>. If you feel your issue may fall in that category, feel free to send things over after you post this issue and reference the issue in your email._

- `composer.json`
- `storage/logs/web.log` (or a zip of the whole log folder)
- An export of your database (or, if you can't share the whole db, the specific Sprout tables)

**Comment by BenParizek** [comment]
@anchovy Sprout Import was discontinued and we currently don't have a supported way to import redirects. You would need to write a custom script at the moment. It is on my list to add an easy way to do this again, but I can't promise any timelines right now.

**Comment by BenParizek** [comment]
Redirects Import Feature ticket: https://github.com/barrelstrength/craft-sprout-redirects/issues/33
